# Generated by Django 4.2.1 on 2023-12-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_category_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
