# Generated by Django 4.2.1 on 2024-01-11 18:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0006_command'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Command',
            new_name='Order',
        ),
    ]
