# Generated by Django 4.2.1 on 2024-01-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_rename_command_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiration_date',
            field=models.CharField(max_length=5),
        ),
    ]
