# Generated by Django 4.2.1 on 2024-01-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_order_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=30),
        ),
    ]
