# Generated by Django 4.2.1 on 2024-01-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_id',
            field=models.CharField(max_length=16),
        ),
    ]
