# Generated by Django 4.2.1 on 2024-01-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_order_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
